name: Android CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths-ignore:
      - "/ios/**"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "/ios/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter pub get
      working-directory: ./example
    - run: echo "${{ secrets.MAPTILER_KEY }}" > assets/maptiler.txt
    - run: flutter build apk
      working-directory: ./example
    - run: flutter build appbundle
      working-directory: ./example
    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: example/build/app/outputs/flutter-apk/app-release.apk
    - name: Upload App Bundle artifact
      uses: actions/upload-artifact@v3
      with:
        name: appbundle
        path: example/build/app/outputs/bundle/release/app-release.aab
